# Node Image for docker on which code will execute
image: node:latest

# This is the stages / task to perfom in jobs
stages:
  - lint
  - test

cache:
  paths:
    - node_modules/
  
before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint:fix

test:
  stage: test
  script:
    - npm run tests
